blog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blogs.urls',namespace='blogs')),
    path('users/',include('users.urls',namespace='users'))
]

blogs/urls.py
"""defines url patterns for blogs"""

from django.urls import path
from . import views

app_name="blogs"
urlpatterns=[
    path('',views.home,name='home'),
    path('add_post/',views.add_post,name='add_post'),
    path('edit_post/<int:post_id>',views.edit_post,name='edit_post')

]

users/urls.py
"""defines url patterns for users"""

from django.urls import path
from django.contrib.auth.views import LoginView
from . import views

app_name="users"
urlpatterns=[
    path('login/',LoginView.as_view(template_name="users/login.html"),
    name="login"),
    path('logout/',views.logout_view,name="logout"),
    path('register/',views.register,name="register"),
    path('profile/<int:post_owner_id>',views.profile,name="profile")

]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

class BlogPost(models.Model):
    """user's posts """
    title=models.CharField(max_length=20)
    text=models.TextField()
    date_added=models.DateTimeField(auto_now_add=True)
    owner=models.ForeignKey(User,models.CASCADE)

    def __str__(self):
        """string representation of the blog's post"""
        return self.text[:50]+"..."

users/models.py
from django.db import models
from django.contrib.auth.models import User

class Bio(models.Model):
    """biography of users"""
    text=models.CharField(max_length=100)
    owner=models.ForeignKey(User,models.CASCADE)

    def __str__(self):
        return self.text

blogs/forms.py
from django import forms
from .models import BlogPost
from users.models import Bio

class PostForm(forms.ModelForm):
    """form for adding a post"""
    title=forms.CharField()
    text=forms.CharField(widget=forms.Textarea(attrs={'cols': 60}))
    class Meta:
        model=BlogPost
        fields=['title','text']
        label={'text':''}
        #widgets = {'text': forms.Textarea(attrs={'cols': 85})}

class BioForm(forms.ModelForm):
    """form for user biography"""
    text=forms.CharField(widget=forms.Textarea(attrs={'cols':60}))
    class Meta:
        model=Bio
        fields=['text']
        label={'text': ''}

blogs/views.py
from django.shortcuts import render
from .models import BlogPost
from .forms import PostForm
from django.http import HttpResponseRedirect,Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

def home(request):
    """home page showing all posts made"""
    posts=BlogPost.objects.order_by('-date_added')
    #to make users to see only their posts, 
    #posts=BlogPost.objects.filter(owner=request.user).oder_by('-date_added')
    context={'posts':posts}
    return render(request,"blogs/home.html",context)

@login_required
def add_post(request):
    """enable a form for the user to add a post"""

    if request.method != "POST":
        """no data submitted,generate blank form """
        form=PostForm()

    else :
        """post data submitted, process data """ 
        form=PostForm(data=request.POST)

        if form.is_valid():
            new_post=form.save(commit=False)
            new_post.owner=request.user
            new_post.save()
            return HttpResponseRedirect(reverse("blogs:home"))

    context={'form':form}
    return render(request,"blogs/add_post.html",context)       

@login_required
def edit_post(request,post_id):
    """edit an existing post"""
    post=BlogPost.objects.get(id=post_id)
    
    if post.owner != request.user:
        raise Http404

    if request.method !="POST":
        """generate already filled form from previous request"""
        form=PostForm(instance=post)

    else:
        """new post data submitted, process"""
        form=PostForm(instance=post,data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("blogs:home"))
    context={'form':form,'post':post}
    return render(request,"blogs/edit_post.html",context)

users/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect 
from django.contrib.auth import logout,login,authenticate
from django.contrib.auth.forms import UserCreationForm
from blogs.forms import BioForm
from .models import Bio
from blogs.models import BlogPost
from django.contrib.auth.decorators import login_required

def logout_view(request):
    """logout the user"""
    logout(request)
    return HttpResponseRedirect(reverse("blogs:home"))

def register(request):
    """register a new user"""

    if request.method != "POST":
        """submit a blank registration form"""
        form=UserCreationForm()

    else:
        """process POST data"""
        form=UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user=form.save()
            authenticated_user=authenticate(username=new_user.username,
            password=request.POST['password1'])
            login(request,authenticated_user)

            return HttpResponseRedirect(reverse("blogs:home"))
    context={"form":form}
    return render(request,"users/register.html",context)  

@login_required
def profile(request,post_owner_id):
    """the user profile page"""
    bio=Bio.objects.filter(owner=post_owner_id)

    #if  bio.text != True :

    posts=BlogPost.objects.filter(owner= post_owner_id).order_by("-date_added")
    post1=posts[0] 
    
    context={"bio":bio,"posts":posts,"post1":post1}

    return render(request,"users/profile.html",context)

blogs/templates/blogs/add_post.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
<h2>Add Post:</h2>
{% endblock header%}

{% block content %}

<form action="{% url 'blogs:add_post' %}" method="post" class="form">
    {% csrf_token %}
    
    {% bootstrap_form form %}
    
    {% buttons %}
    <button name="submit" class="btn btn-primary" style="background-color: grey;">Post</button>
    {% endbuttons %}
</form>

{% endblock content %}

blogs/templates/blogs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="eng">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>Xander-Blog</title>
{% bootstrap_css %}
{% bootstrap_javascript %}
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
            data-toggle="collapse" data-target="#navbar"
            aria-expanded="false" aria-controls="navbar"></button>
            <a class="navbar-brand" href="{% url 'blogs:home' %}">Home</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">

            <ul class="nav navbar-nav navbar-right ">
                {% if user.is_authenticated %}
                Hello, {{user.username}} <a href="{% url 'users:logout' %}"> Log out</a>
                {% else %}
                <li><a href="{% url 'users:register' %}">register</a></li> 
                <li><a href="{% url 'users:login' %}">login</a></li>
                {% endif %}

            </ul>
            
        </div><!-- /.nav-collapse -->
    </div>
</nav>

<div class="container">
    <div class="page-header">
        {%block header%}{% endblock header %}
    </div>
    <div>
        {%block content%}{% endblock content %}
    </div>
</div><!-- /container -->

</body>

</html>

blogs/templates/blogs/edit_post.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
<h2>Edit Post:</h2>
{% endblock header%}

{% block content %}

<form action="{% url 'blogs:edit_post' post.id %}" method="post" class="form">
    {% csrf_token %}
    
    {% bootstrap_form form %}
    
    {% buttons %}
    <button name="submit" class="btn btn-primary" style="background-color: grey;">save</button>
    {% endbuttons %}

</form>

{% endblock content %}

blogs/templates/blogs/home.html
{% extends "blogs/base.html" %}
{%block header%}
{% if user.is_authenticated %}

<div style="width: 30%;  
padding: 10px;">
<a style="padding: 3px; color: dimgray; font-size: 32px;" href="{% url 'users:profile' user.id %}">
   
    <i class="fa fa-user-circle">{{user.username}}</i>  
</a>
</div>
{% endif %}
<div class="jumbotron">
    <h2>what's on your mind ? Post it</h2>
    <div style="background:darkgray; width: 15%; border-radius: 10px;">
        <a href="{% url 'blogs:add_post' %}" >
        <i class="fa fa-plus"> Add Post</i></a>
    </div>
    
</div>
{% endblock header%}

{% block content %}
{% for post in posts %}
<div class="panel panel-default">
    
    <div class="panel-heading">    
        <h3>
            {{post.title}} - {{post.date_added |date:'M d, Y H:i'}}
            <h4>posted by <a style="color:cadetblue;"
                 href="{% url 'users:profile' post.owner.id %}">{{post.owner}}</a></h4>
            <small>
                <a href="{% url 'blogs:edit_post' post.id %}">
                    <i class="fa fa-edit"> Edit Post</i></a>
            </small>
        </h3>    
    </div>

    <div class="panel-body">
        {{post.text | linebreaks}}
    </div>
    
</div><!-- panel-->
{% endfor %}


{% endblock content %}

users/templates/users/login.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}


{% block header %}
<h2>Log in to your account</h2>
{% endblock header %}

{% block content %}

<form action="{% url 'users:login' %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form%}
    
    {% buttons %}
    <button name="submit" class="btn btn-primary" style="background-color: grey;">Log in</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'blogs:home' %}"/>
</form>

{% endblock content %}

users/templates/users/profile.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header %}

<h3>{{post1.owner}}</h3>
{% endblock header %}

{% block content %}

{% if bio.text %}
<div>
    <p>Bio:</p>
    <p>{{bio.text}}</p>
    <p>edit_bio</p>
</div>
{% else %}
<p>add bio</p>
{% endif %}
{% for post in posts %}

<div class="panel panel-default">
    
    <div class="panel-heading">    
        <h3>
            {{post.title}} - {{post.date_added |date:'M d, Y H:i'}}
            <h4>posted by {{post.owner}}</h4>
            <small>
                <a href="{% url 'blogs:edit_post' post.id %}">
                    <i class="fa fa-edit"> Edit Post</i></a>
            </small>
        </h3>    
    </div>

    <div class="panel-body">
        {{post.text | linebreaks}}
    </div>
    
</div><!-- panel-->
{% empty %}
<p>No posts has been made yet</p>
{% endfor %}


{% endblock content %}

users/templates/users/register.html
{% extends "blogs/base.html" %}

{% block content %}

<form action="{% url 'users:register' %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Register</button>
    <input type="hidden" name="next" value="{% url 'blogs:home' %}" /> 
</form>

{% endblock content %}